// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TrackMyAct.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128193756_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mark")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("EventId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventPlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InterestEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedAcception")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizerEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventPlaceId");

                    b.HasIndex("InterestEntityId");

                    b.HasIndex("OrganizerEntityId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventEntityParticipantEntity", b =>
                {
                    b.Property<int>("AcceptedParticipantsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipationsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AcceptedParticipantsId", "ParticipationsId");

                    b.HasIndex("ParticipationsId");

                    b.ToTable("EventParticipants", (string)null);
                });

            modelBuilder.Entity("EventEntityParticipantEntity1", b =>
                {
                    b.Property<int>("ArchiveEventsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArchiveEventsId", "ParticipantEntityId");

                    b.HasIndex("ParticipantEntityId");

                    b.ToTable("ParticipantArchiveEvents", (string)null);
                });

            modelBuilder.Entity("EventEntityParticipantEntity2", b =>
                {
                    b.Property<int>("ParticipantRequestsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantRequestsId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParticipantRequestsId", "ParticipantRequestsId1");

                    b.HasIndex("ParticipantRequestsId1");

                    b.ToTable("EventParticipantRequests", (string)null);
                });

            modelBuilder.Entity("EventEntityParticipantEntity3", b =>
                {
                    b.Property<int>("OrganizerRequestsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganizerRequestsId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrganizerRequestsId", "OrganizerRequestsId1");

                    b.HasIndex("OrganizerRequestsId1");

                    b.ToTable("EventOrganizerRequests", (string)null);
                });

            modelBuilder.Entity("InterestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("InterestEntityParticipantEntity", b =>
                {
                    b.Property<int>("InterestsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InterestsId", "ParticipantsId");

                    b.HasIndex("ParticipantsId");

                    b.ToTable("ParticipantInterests", (string)null);
                });

            modelBuilder.Entity("OrganizerEntityParticipantEntity", b =>
                {
                    b.Property<int>("OrganizerSubscriptionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscribersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrganizerSubscriptionsId", "SubscribersId");

                    b.HasIndex("SubscribersId");

                    b.ToTable("OrganizerSubscriptions", (string)null);
                });

            modelBuilder.Entity("PlaceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailableTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("UserEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OrganizerEntity", b =>
                {
                    b.HasBaseType("UserEntity");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Organizer");
                });

            modelBuilder.Entity("ParticipantEntity", b =>
                {
                    b.HasBaseType("UserEntity");

                    b.Property<DateTime>("BirthdayDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerifed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Participant");
                });

            modelBuilder.Entity("CommentEntity", b =>
                {
                    b.HasOne("ParticipantEntity", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EventEntity", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OrganizerEntity", "Organizer")
                        .WithMany("Comments")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Author");

                    b.Navigation("Event");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("EventEntity", b =>
                {
                    b.HasOne("PlaceEntity", "EventPlace")
                        .WithMany("Events")
                        .HasForeignKey("EventPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterestEntity", null)
                        .WithMany("Events")
                        .HasForeignKey("InterestEntityId");

                    b.HasOne("OrganizerEntity", null)
                        .WithMany("ArchiveEvents")
                        .HasForeignKey("OrganizerEntityId");

                    b.HasOne("OrganizerEntity", "Organizer")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventPlace");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("EventEntityParticipantEntity", b =>
                {
                    b.HasOne("ParticipantEntity", null)
                        .WithMany()
                        .HasForeignKey("AcceptedParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventEntity", null)
                        .WithMany()
                        .HasForeignKey("ParticipationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventEntityParticipantEntity1", b =>
                {
                    b.HasOne("EventEntity", null)
                        .WithMany()
                        .HasForeignKey("ArchiveEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParticipantEntity", null)
                        .WithMany()
                        .HasForeignKey("ParticipantEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventEntityParticipantEntity2", b =>
                {
                    b.HasOne("ParticipantEntity", null)
                        .WithMany()
                        .HasForeignKey("ParticipantRequestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventEntity", null)
                        .WithMany()
                        .HasForeignKey("ParticipantRequestsId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventEntityParticipantEntity3", b =>
                {
                    b.HasOne("ParticipantEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizerRequestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizerRequestsId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterestEntityParticipantEntity", b =>
                {
                    b.HasOne("InterestEntity", null)
                        .WithMany()
                        .HasForeignKey("InterestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParticipantEntity", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrganizerEntityParticipantEntity", b =>
                {
                    b.HasOne("OrganizerEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizerSubscriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParticipantEntity", null)
                        .WithMany()
                        .HasForeignKey("SubscribersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterestEntity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("PlaceEntity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("OrganizerEntity", b =>
                {
                    b.Navigation("ArchiveEvents");

                    b.Navigation("Comments");

                    b.Navigation("OrganizedEvents");
                });

            modelBuilder.Entity("ParticipantEntity", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
